Brand update, Issue #1490
ni/nimi-python pull request #1592
Opened 2021-04-22 21:09 UTC by imranadamjee

* As per the issue, updated to NI in the README's.
* GitHub wiki was good from the start.
* Updated the copyright to the recommendation from ni-central.

- [ x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).

- [x ] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.

TODO: Check the above box with an 'x' if considered if there were any and then documented client facing changes in [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md). Strike through if this is not a relevant client facing change.

- [x ] I've added tests applicable for this pull request

TODO: Check the above box with an 'x' indicating you have considered and added any applicable system or unit tests. Strike through if you considered and decided additional tests were not warranted.

### What does this Pull Request accomplish?

TODO: Include high-level description of the changes in this pull request.

### List issues fixed by this Pull Request below, if any.

TODO: List of issues.

* Fix #xxx
* Fix #yyy

### What testing has been done?

TODO: Detail what testing has been done to ensure this submission meets requirements.

2021-04-23 15:07 UTC, marcoskirsch requested changes
You hand edited the generated files, but not the templates.
You need to modify the templates, run codegeneration, then commit that for the PR.
Thanks!

2021-04-26 15:26 UTC, sbethur commented
ok to test

2021-04-26 15:27 UTC, sbethur commented
Update the description and reference the relevant GitHub issue

2021-04-27 18:20 UTC, sbethur commented
test this please

2021-06-10 21:30 UTC, sbethur requested changes

2021-06-10 21:30 UTC, sbethur commented on LICENSE
> +© 2021 National Instruments Corporation. All rights reserved
Follow the format prescribed in https://opensource.org/licenses/mit-license.php, with `National Instruments Corporation` as the copyright holder.

2021-06-10 21:30 UTC, sbethur commented on LICENSE
> +NI-ModInst, NI-TClk are trademarks of NI.
National Instruments Corporation

2021-06-10 21:30 UTC, sbethur commented on build/templates/conf.py.mako
> +copyright = '2017-${current_year}, NI'
National Instruments Corporation

2021-06-10 21:30 UTC, sbethur commented on src/niswitch/metadata/config.py
> +    'session_class_description': 'An NI-SWITCH session to a NI Switch Module',
```suggestion
    'session_class_description': 'An NI-SWITCH session to an NI Switch Module',
```

Applies to other places too.

2021-06-10 21:30 UTC, sbethur commented on src/nidigital/metadata/attributes.py
> +            'description': 'Returns a string ("NI") that contains the name of the manufacturer of the digital pattern instrument.\n'
Revert this change. The software still returns the expanded name.

2021-06-10 21:30 UTC, sbethur commented on src/nidigital/metadata/attributes.py
> +            'description': 'Returns a string ("NI") that contains the name of the vendor that supplies the NI-Digital Pattern Driver.\n'
Revert this change. The software still returns the expanded name.

2021-06-10 21:30 UTC, sbethur commented on src/nidcpower/examples/nidcpower_advanced_sequence.py
> +    parser.add_argument('-n', '--resource-name', default='PXI1Slot2', help='Resource name of a NI SMU')
Why did the default change? Looks like a merge issue.

2022-08-01 19:50 UTC, sbethur commented
The changes here were submitted by #1714 and #1734.

2022-08-01 19:50 UTC, closed without merging