Stop using persistent-simulated device in nifgen system tests
ni/nimi-python pull request #1598
Opened 2021-05-05 23:31 UTC by sbethur

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).

~- [ ] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~

~- [ ] I've added tests applicable for this pull request~

### What does this Pull Request accomplish?

Stop using persistent-simulated device in nifgen system tests, now that the internal issues 227842 and 999932 are fixed.

### List issues fixed by this Pull Request below, if any.

* Fix #1375 
* Fix #1376 

### What testing has been done?

System tests will run as part of PR pipeline.

2021-05-10 15:16 UTC, marcoskirsch requested changes
It appears system tests need a bit more love.

2021-05-10 16:10 UTC, sbethur commented
test this please

2021-05-10 19:56 UTC, sbethur commented
test this please

2021-05-11 19:13 UTC, sbethur commented
This is blocked until NI-FGEN driver runtime is updated to beyond 20.0 on nimi-bot.

2022-01-06 22:50 UTC, sbethur commented
/AzurePipelines run

2023-09-10 16:12 UTC, ni-jfitzger commented
Thanks for your work on this @sbethur. I'm reimplementing it against master and fixing any remaining issues in #2010, so I'm closing this.

2023-09-10 16:12 UTC, closed without merging