NI-DCPower: Add new non-LCR attributes and enum
ni/nimi-python pull request #1706
Opened 2022-04-05 11:35 UTC by olsl21

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
- [x] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.
~~- [ ] I've added tests applicable for this pull request~~

### What does this Pull Request accomplish?

- Add `aperture_time_auto_mode` and `autorange_maximum_delay_after_range_change` attributes
- Add `aperture_time_auto_mode` enum
- Update CHANGELOG

### What testing has been done?

Tested that the attributes can be retrieved correctly.
```
>>> with nidcpower.Session(resource_name='4137_sim', channels='0', options='Simulate=1, DriverSetup=Model:4137; BoardType:PXIe') as smu:
...     print(smu.aperture_time_auto_mode)
...
ApertureTimeAutoMode.OFF
>>> with nidcpower.Session(resource_name='4162_sim', channels='0', options='Simulate=1, DriverSetup=Model:4162; BoardType:PXIe') as smu:
...     print(smu.autorange_maximum_delay_after_range_change)
...
0:00:00.100000
```

2022-04-05 19:32 UTC, marcoskirsch approved these changes

2022-04-05 19:34 UTC, marcoskirsch requested changes
It appears the metadata was modified.

> # This file is generated from NI-DCPower API metadata version 21.0.0f353

It should be exact copy of the internal NI artifact.
Instead, copy the metadata from the internal artifact. This may require you to add some add-on metadata to keep other things from showing up.

As a matter of fact, consider first updating the metadata in its own PR.

2022-04-06 17:54 UTC, sbethur commented
/AzurePipelines run

2022-05-23 16:59 UTC, sbethur approved these changes

2022-05-23 16:59 UTC, merged