Allow no-codegen method to have method_name_for_doc
ni/nimi-python pull request #1709
Opened 2022-04-06 07:15 UTC by olsl21

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
- [x] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.
- [x] I've added tests applicable for this pull request

### What does this Pull Request accomplish?

- Update `_add_python_method_name` to skip the assertion for `method_name_for_documentation` if the `codegen_method` of the function is "no"
- Add unit test for this change

### List issues fixed by this Pull Request below, if any.

### What testing has been done?

All the build tests (including the updated ones) passed

2022-04-06 17:55 UTC, sbethur commented
/AzurePipelines run

2022-04-06 18:58 UTC, marcoskirsch requested changes

2022-04-07 06:07 UTC, olsl21 commented on CHANGELOG.md
> +        * Allow functions with `codegen_method` set to "no" to have `method_name_for_documentation` defined
I see, I have reverted the changes on CHANGELOG.md with the latest commit.

2022-04-15 17:24 UTC, marcoskirsch approved these changes

2022-04-19 03:59 UTC, sbethur commented
/AzurePipelines run

2022-04-19 05:18 UTC, sbethur approved these changes

2022-04-19 05:27 UTC, merged