Remove RLock from nidcpower
ni/nimi-python pull request #1711
Opened 2022-04-06 16:41 UTC by dylan-matthew-turner

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
- [x] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.
- [x] I've added tests applicable for this pull request

### What does this Pull Request accomplish?

- Adds test failure for using RLock
- Removes src/nidcpower/templates/session.py/fancy_lock.py.mako and src/nidcpower/templates/session.py/fancy_unlock.py.mako
- Modifies functions.py to use lock/unlock instead of removed fancy_lock/fancy_unlock

### List issues fixed by this Pull Request below, if any.

- Fix #1596 

### What testing has been done?

- Test targeting data stored to use RLock fails in master but succeeds after changes applied
- All previous system tests pass

2022-04-06 17:55 UTC, sbethur commented
/AzurePipelines run

2022-04-06 19:03 UTC, marcoskirsch commented
@dylan-matthew-turner the title and description paraphrase the diff. Please modify to explain why the change is being made and the high level purpose, which adds value.

Example: "Remove workaround for niDCPower_LockSession / niDCPower_UnlockSession"...

2022-04-06 19:07 UTC, marcoskirsch requested changes
PLease fix title and description

2022-04-07 18:33 UTC, sbethur requested changes

2022-04-07 18:33 UTC, sbethur commented on CHANGELOG.md
> +        * Addressed [#1596](https://github.com/ni/nimi-python/issues/1596) by removing RLock replacements for session.py::_SessionBase::lock/unlock
Changelog should be used only for customer-visible changes.

The use of RLock had a minor enough customer impact (Access to multiple nidcpower sessions are serialized) that we decided not to mention in the Changelog. So removal of it doesn't need to be mentioned either.

2022-04-07 18:33 UTC, sbethur commented on src/nidcpower/system_tests/test_system_nidcpower.py
> +def test_no_underlying_rlock(session):
This is a good test to run as part of "dev testing" but don't think it makes a good system test to be used for regression. Outside of this PR, the test doesn't provide sufficient context or utility for maintainers. I'd say remove it.

2022-04-07 21:14 UTC, marcoskirsch approved these changes
Waiting on changes based on Shreyas' feedback.

2022-04-08 15:06 UTC, sbethur commented
/AzurePipelines run

2022-04-08 20:38 UTC, sbethur approved these changes

2022-04-08 20:39 UTC, merged