Remove --universal wheel option to prevent "py2" compatibility tag
ni/nimi-python pull request #1718
Opened 2022-04-07 19:46 UTC by mmorin-ni

### What does this Pull Request accomplish?
Removes python2 compatibility from wheel names as python 2 is no longer supported.
Done via removing --universal option when creating the .whl files
Also removed the reference to "py2" in the CONTRIBUTING.md 

### List issues fixed by this Pull Request below, if any.
Fixes Issue: #1641

### What testing has been done?
Built locally and checked that the codegen output wheel file excludes the py2 compatibility tag.

2022-04-07 19:49 UTC, sbethur commented
/AzurePipelines run

2022-04-07 21:19 UTC, marcoskirsch approved these changes

2022-04-11 21:36 UTC, sbethur requested changes
Please update https://github.com/ni/nimi-python/blob/243a3b6ac8595840fdf94e11149346f26829934f/build/templates/tox-system_tests.ini.mako#L49 and rerun the build so [these ](https://github.com/search?q=universal+repo%3Ani%2Fnimi-python+path%3Agenerated&type=Code&ref=advsearch&l=&l=) generated files are updated.

2022-04-12 21:23 UTC, danieljllo commented
Should abandon this Pull Request since another one has been created for the same issue (#1727)

2022-04-13 15:47 UTC, closed without merging