NIFAKE: Update metadata, fix _mock_helper
ni/nimi-python pull request #1750
Opened 2022-06-09 10:31 UTC by olsl21

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
~- [ ] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~
~- [ ] I've added tests applicable for this pull request~

### What does this Pull Request accomplish?

- Update nifake metadata
  - Create placeholder custom type implementation files for the new `custom_struct_typedef` and `custom_struct_nested_typedef` custom types
  - Update nifake.mak to copy the custom type implementation files so that the build can succeed
- Fix `_mock_helper.py.mako` codegen logic for functions with custom type parameter to use the actual parameter name instead of hardcoded "cs"

### What testing has been done?

Local build succeeded.

2022-06-09 10:32 UTC, olsl21 commented on src/nifake/metadata/attributes.py
> +# This file is generated from NI-FAKE API metadata version 22.5.0d9999
I'll update this to an official export once the internal PR gets approved and merged.

2022-06-09 20:28 UTC, marcoskirsch commented
What is this PR really doing?
It's not just "updating metadata", it's adding new things to it. This is the "what" and "updating metadata" is the how.
Please improve the description and call the fake driver "NI-FAKE" (similar to NI-DMM or NI-FGEN).

2022-06-09 20:30 UTC, marcoskirsch commented
Is it possible to do this in smaller, distinct, single purpose PRs?

First one would be, it seems, to update NI-FAKE metadata to something newer but that doesn't attempt to exercise the new capabilities you are adding to nimi-python (namely the ability for enums to specify what values they convert to when exposed in nimi-python APIs).

2022-06-10 02:19 UTC, olsl21 commented on src/nifake/metadata/attributes.py
> +# This file is generated from NI-FAKE API metadata version 22.5.0d9999
I will split this PR into smaller PRs and this PR will now updata the NI-FAKE metadata to 22.5.0d9

2022-06-10 04:36 UTC, olsl21 commented
> Is it possible to do this in smaller, distinct, single purpose PRs?
> 
> First one would be, it seems, to update NI-FAKE metadata to something newer but that doesn't attempt to exercise the new capabilities you are adding to nimi-python (namely the ability for enums to specify what values they convert to when exposed in nimi-python APIs).

I've split it into two PRs (i.e. this PR which updates the metadata to 22.5.0d9 (without the new enum with converter and its related attribute) and #1751 which adds the new enum with converter and its related attribute).

> What is this PR really doing? It's not just "updating metadata", it's adding new things to it. This is the "what" and "updating metadata" is the how. Please improve the description and call the fake driver "NI-FAKE" (similar to NI-DMM or NI-FGEN).

This PR is now updating the metadata to 22.5.0d9 with new custom types, enum and functions, as well as some fixes. I have updated the PR description to list out the changes in the metadata more explicitly.

2022-06-15 15:07 UTC, marcoskirsch requested changes
There are two methods being added to `nifake` in this PR but they aren't unit tested.
I think we need a more realistic struct so that it can be properly exercised.

2022-06-16 11:04 UTC, olsl21 commented
> There are two methods being added to `nifake` in this PR but they aren't unit tested. I think we need a more realistic struct so that it can be properly exercised.

I have completed the implementations for the new custom types and added unit tests for the two new methods in my latest commit.

2022-06-16 16:14 UTC, marcoskirsch commented
[CI Error](https://github.com/ni/nimi-python/pull/1750/checks?check_run_id=6917155578)
```
The following code generated files do not match what is commited to Git. Run codegen and include the generated files in the PR.
 M generated/nifake/nifake/unit_tests/test_session.py
```

2022-06-17 03:42 UTC, olsl21 commented
Sorry for the CI error, I have added in the missing code generated file.

2022-06-17 19:12 UTC, sbethur approved these changes

2022-06-17 20:53 UTC, marcoskirsch approved these changes

2022-06-20 02:43 UTC, olsl21 commented on src/nifake/custom_types/custom_struct_nested_typedef.py
> +# These custom type classes are created as placeholders
Oh, this comment was actually from before I added the full implementation for these new custom types. I've removed it in my latest commit.

2022-06-20 18:08 UTC, merged