Stop claiming easy_install support.
ni/nimi-python pull request #1947
Opened 2023-04-17 14:22 UTC by ni-jfitzger

- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
- ~[ ] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~
- ~[ ] I've added tests applicable for this pull request~.

### What does this Pull Request accomplish?
- Remove mentions of deprecated easy_install option.
- [Setuptools deprecated the easy_install command in 2021] (https://setuptools.pypa.io/en/latest/history.html#v58-3-0)

### List issues fixed by this Pull Request below, if any.
None

### What testing has been done?
None

2023-04-17 15:44 UTC, ni-jfitzger commented on generated/nifgen/README.rst
> -
Should I have left another blank line?

2023-04-17 18:54 UTC, marcoskirsch requested changes

2023-04-17 18:54 UTC, marcoskirsch commented on generated/nifgen/README.rst
> -
I think so

2023-04-17 18:54 UTC, marcoskirsch commented
Some system tests failed, please check why.

2023-04-24 13:28 UTC, marcoskirsch commented on CHANGELOG.md
> +        * `easy_install` support dropped.
FWIW, this is under "Removed" which makes it redundante to say "dropped" in the line item.

2023-04-26 14:17 UTC, merged